### ISSUE TITLE
Configuring the database (PostgreSQL + SQLAlchemy)

### ISSUE THREAD

**Issue by valay-shah** [nyu-devops-fall2021-orders/orders#4]
**As a** developer 
**I need** a database 
**So that** I can store my data in one place and retrieve it when necessary.

**Details & Assumptions:** 
*  The database that I am using is running in the environment*
*  We can use PostgreSQL as Orders would contain the same values so the database can be relational*
* We can also use SQLAlchemy to interact with PostgreSQL*
* We will have to create a basic order model to start with *

**Acceptance Criteria:**

```gherkin
Given some sql query
When I run the query
Then it should insert in a database
```

**Comment by shantanu-dahiya** [comment]
Should we use MySQL or MongoDB? The professor mentioned that orders are usually relational and don't have too many disparate fields. We could go with SQL. Do you think MySQL would be better or other SQL flavours like PostgreSQL?
