### ISSUE TITLE
Implement an Action endpoint route

### ISSUE THREAD

**Issue by valay-shah** [nyu-devops-fall2021-orders/orders#40]
**As a** User
**I need** Action endpoint route 
**So that** Can change the status 

**Details & Assumptions:** 
* ...

**Acceptance Criteria:**

```gherkin
Given [some initial state]
When [some event]
Then [some measurable outcome]
```

**Comment by abhishek-rr** [comment]
Clarify what is needed here exactly.
1) Change status with PUT.
